#!/bin/bash

if [ $# -eq 0 ]
then
  echo "usage: csvgrep <expr> <file> [grep options]"
  exit 1
fi

EXPR="$1"
CSVFILE=${2:-'-'}
HEADTMP="$(mktemp)"

shift
shift

head -n1 "$CSVFILE" > "$HEADTMP"
grep "$EXPR" "$CSVFILE" $@ | cat $HEADTMP -

